// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';


var enter_key = 13;

var escape_key = 27;

var storageKey = "todos-reason-react";

exports.enter_key = enter_key;
exports.escape_key = escape_key;
exports.storageKey = storageKey;
/* No side effect */
