// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Cn = require("re-classnames/src/Cn.bs.js");
var Curry = require("bs-platform/lib/js/curry.js");
var Utils = require("./Utils.bs.js");
var React = require("react");

function TodoItem(Props) {
  var todo = Props.todo;
  var editing = Props.editing;
  var onCancel = Props.onCancel;
  var onToggle = Props.onToggle;
  var onDestroy = Props.onDestroy;
  var onSave = Props.onSave;
  var onEdit = Props.onEdit;
  var match = React.useReducer((function (_oldEditText, newEditText) {
          return newEditText;
        }), "");
  var setEditText = match[1];
  var editText = match[0];
  return React.createElement("li", {
              className: Cn.make(/* :: */[
                    Cn.ifTrue("completed", todo[/* completed */2]),
                    /* :: */[
                      Cn.ifTrue("editing", editing),
                      /* [] */0
                    ]
                  ])
            }, React.createElement("div", {
                  className: "view"
                }, React.createElement("input", {
                      className: "toggle",
                      checked: todo[/* completed */2],
                      type: "checkbox",
                      onChange: (function (_event) {
                          return Curry._1(onToggle, /* () */0);
                        })
                    }), React.createElement("label", {
                      onDoubleClick: (function ($$event) {
                          Curry._1(onEdit, /* () */0);
                          return Curry._1(setEditText, todo[/* title */1]);
                        })
                    }, todo[/* title */1]), React.createElement("button", {
                      className: "destroy",
                      onClick: (function (_event) {
                          return Curry._1(onDestroy, /* () */0);
                        })
                    })), React.createElement("input", {
                  className: "edit",
                  value: editText,
                  onKeyDown: (function ($$event) {
                      var $$event$1 = $$event;
                      var match = $$event$1.keyCode;
                      if (match !== 13) {
                        if (match !== 27) {
                          return /* () */0;
                        } else {
                          return Curry._1(onCancel, /* () */0);
                        }
                      } else {
                        return Curry._1(onSave, editText);
                      }
                    }),
                  onBlur: (function ($$event) {
                      return Curry._1(onSave, editText);
                    }),
                  onChange: (function ($$event) {
                      return Curry._1(setEditText, Utils.valueFromEvent($$event));
                    })
                }));
}

var make = TodoItem;

exports.make = make;
/* react Not a pure module */
