// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var Utils = require("./Utils.bs.js");
var React = require("react");

function TodoFooter(Props) {
  var count = Props.count;
  var completedCount = Props.completedCount;
  var nowShowing = Props.nowShowing;
  var onClearCompleted = Props.onClearCompleted;
  var match = completedCount === 0;
  var clearButton = match ? null : React.createElement("button", {
          className: "clear-completed",
          onClick: (function (_event) {
              return Curry._1(onClearCompleted, /* () */0);
            })
        }, "Clear completed");
  var activeTodoSize = count - completedCount | 0;
  var match$1 = nowShowing === /* All */0;
  var match$2 = nowShowing === /* Active */1;
  var match$3 = nowShowing === /* Completed */2;
  return React.createElement("footer", {
              className: "footer"
            }, React.createElement("span", {
                  className: "todo-count"
                }, React.createElement("strong", undefined, String(activeTodoSize)), Utils.pluralize(activeTodoSize, " todo") + " left"), React.createElement("ul", {
                  className: "filters"
                }, React.createElement("li", undefined, React.createElement("a", {
                          className: match$1 ? "selected" : "",
                          href: "#/"
                        }, "All")), React.createElement("li", undefined, React.createElement("a", {
                          className: match$2 ? "selected" : "",
                          href: "#/active"
                        }, "Active")), React.createElement("li", undefined, React.createElement("a", {
                          className: match$3 ? "selected" : "",
                          href: "#/completed"
                        }, "Completed"))), clearButton);
}

var make = TodoFooter;

exports.make = make;
/* react Not a pure module */
